export const ADD_CHARACTER = 'ADD_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
export const DELETE_ALLCHARACTER = 'DELETE_ALLCHARACTER';
export const ADD_CHARACTER_FAVOURITE = 'ADD_CHARACTER_FAVOURITE';
export const DELETE_CHARACTER_FAVOURITE = 'DELETE_CHARACTER_FAVOURITE';
export const DELETE_ALL_CHARACTER_FAVOURITE = 'DELETE_ALL_CHARACTER_FAVOURITE';
export const FILTER = 'FILTER';
export const ORDER = 'ORDER';
